# Generated by Django 6.0.3 on 2026-03-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_app', '0002_remove_staffnote_date_remove_staffnote_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(blank=True),
        ),
    ]
