# Generated by Django 6.0.3 on 2026-03-18 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffnote',
            name='date',
        ),
        migrations.RemoveField(
            model_name='staffnote',
            name='request',
        ),
        migrations.AddField(
            model_name='staffnote',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='location',
            field=models.CharField(choices=[('Living Room', 'Living Room'), ('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'), ('Balcony', 'Balcony')], max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Fixed', 'Fixed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='urgency',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'High')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffnote',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffnote',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
